name: sync-images

on:
    push:
    # è®¾ç½®å®šæ—¶ä»»åŠ¡ï¼Œæ¯ 31 å¤©è¿è¡Œä¸€æ¬¡
    schedule:
        - cron: "0 0 */31 * *"

jobs:
    job1:
        runs-on: ubuntu-latest
        # env:
        steps:
            - name: Clone repository
              uses: actions/checkout@v4
            - name: get images and publish ğŸš©è·å–é•œåƒï¼Œè‡ªåŠ¨æ‰©å®¹å¹¶å‘å¸ƒ
              shell: bash
              run: |
                  date
                  echo 'hello there! Ready to make new images--å‡†å¤‡è‡ªåŠ¨æ‰©å®¹é•œåƒ'
                  source ./index.sh
            - name: "â«ä¸Šä¼ åˆ¶å“"
              uses: actions/upload-artifact@v4
              with:
                  name: æ‰©å®¹åçš„openwrt
                  path: op.img.gz
